#!/usr/bin/env bash
# Add other subdomains to make our life easier, and write a Bash script that will display information about subdomains


function my_function {
    clear
}

my_function

if [ "$#" -eq 1 ]
then
    list="www lb-01 web-01 web-02"

elif [ "$#" -eq 2 ]
then
    list="$2"
fi

for var in $list
do
subdomain="$var.$1"
dig "$subdomain"\
 | grep -A1 "ANSWER SECTION:"\
 | grep "$1"\
 | awk -v var="$var" '{print "The subdomain " var " is a " $4 " record and points to " $5}'
done




# | awk '/diegoorejuela/ {print}'\
