#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" >> /var/www/html/index.html
sudo service nginx start
sudo sed '/server_name/ i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
sudo service nginx start
