#!/usr/bin/env bash
# Install nginx on your web-01 server
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" >> /var/www/html/index.html
sed -i "14i\ \tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
