#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.5
sudo apt-get update
sudo apt-get -y install haproxy=1.5.\*
sudo service haproxy start
sudo echo -e "
frontend haproxynode
         bind *:80
	 mode http
	 default_backend backendnodes

backend backendnodes
         balance roundrobin
         server node1 34.74.88.31:80 check
         server node2 104.196.153.78:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
