#!/usr/bin/env bash
# This script is displaying in 10 times: "bad luck" for the 4th loop iteration
# "good luck" for the 8th loop iteration and "Holberton School" for the other
# iterations
i=1
while [ $i -le 20 ]
do
    case $i in
	4)
	    echo $i
	    echo "bad luck from China"
	    ;;
	9)
	    echo $i
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo $i
	    echo "bad luck from Italy"
	    ;;
	*)
	    echo $i
    esac
    i=$(( i + 1 ))
done
