#!/usr/bin/env bash
# configures an Ubuntu server with the below requirements.
cp /etc/hosts myhosts
sed -i s/127.0.0.1/127.0.0.2/ myhosts
sed -i s/157.240.11.35/8.8.8.8/ myhosts
sudo cp -f myhosts /etc/hosts
