#!/usr/bin/env bash
# configures an Ubuntu server with the below requirements.
cp /etc/hosts myhosts
sed -i s/127.0.0.1/127.0.0.2/ myhosts
echo -e "8.8.8.8\tfacebook.com" >> myhosts
sudo cp -f myhosts /etc/hosts
