#!/usr/bin/env bash
# Run Nginx as Nginx
chown nginx /etc/nginx/nginx.conf
chmod 600 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
#sed -i "1i\\user nginx;" /etc/nginx/nginx.conf
sudo -u nginx service nginx start

#listar puertos = lsof -nP -i | grep LISTEN
# https://stackoverflow.com/questions/42329261/running-nginx-as-non-root-user
